import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  states: [
    "Punjab",
    "Sindh",
    "Khyber Pakhtunkhwa",
    "Gilgit-Baltistan",
    "Azad Kashmir",
    "Balochistan",
    "Islamabad",
    "Federally Administered Tribal Areas",
  ],
  cities: [
    "Abbottabad",
    "Adilpur",
    "Ahmedpur East",
    "Ahmadpur Sial",
    "Akora",
    "Alik Ghund",
    "Alipur Chatha",
    "Alizai",
    "Aman Garh",
    "Amirabad",
    "Arifwala",
    "Ashanagro Koto",
    "Attock Tehsil",
    "Awārān District",
    "Baffa",
    "Badin",
    "Baddomalhi",
    "Bagarji",
    "Bahrain",
    "Bahawalnagar",
    "Bahawalpur",
    "Bakhri Ahmad Khan",
    "Bannu",
    "Bandhi",
    "Barishal",
    "Barkhan",
    "Bārkhān District",
    "Basirpur",
    "Basti Dosa",
    "Bat Khela",
    "Battagram",
    "Battagram District",
    "Begowala",
    "Behra",
    "Bela",
    "Berani",
    "Bhalwal",
    "Bhan",
    "Bhera",
    "Bhimbar",
    "Bhiria",
    "Bhit Shah",
    "Bhopalwala",
    "Bhag",
    "Bhakkar",
    "Bozdar Wada",
    "Bulri",
    "Buner District",
    "Burewala",
    "Chak",
    "Chak Azam Saffo",
    "Chak Jhumra",
    "Chak One Hundred Twenty Nine Left",
    "Chak Thirty-one -Eleven Left",
    "Chak Two Hundred Forty-Nine TDA",
    "Chakwal",
    "Chaman",
    "Chamber",
    "Charsadda",
    "Chawinda",
    "Cherat Cantonement",
    "Chichawatni",
    "Chiniot",
    "Chishtian",
    "Chitral",
    "Chohar Kana",
    "Choa Saidanshah",
    "Chor",
    "Chowki Jamali",
    "Chuhar Jamali",
    "Dadu",
    "Dadhar",
    "Daira Din Panah",
    "Dajal",
    "Dalbandin",
    "Dandot RS",
    "Darya Khan",
    "Darya Khan Marri",
    "Daud Khel",
    "Daultala",
    "Daulatpur",
    "Daur",
    "Dera Bugti",
    "Dera Bugti District",
    "Dera Ghazi Khan",
    "Dera Ismail Khan",
    "Dera Ismāīl Khān District",
    "Dhoro Naro",
    "Dhanot",
    "Dhaunkal",
    "Dhok Awan",
    "Dijkot",
    "Dinan Bashnoian Wala",
    "Dinga",
    "Dipalpur",
    "Diplo",
    "Dokri",
    "Doaba",
    "Dullewala",
    "Dunga Bunga",
    "Dunyapur",
    "Eminabad",
    "Faisalabad",
    "Faqirwali",
    "Faruka",
    "Fazilpur",
    "Ferozewala",
    "Fort Abbas",
    "Gadani",
    "Garh Maharaja",
    "Garhiyasin",
    "Garhi Khairo",
    "Ghauspur",
    "Gharo",
    "Ghotki",
    "Gilgit",
    "Gojra",
    "Goth Garelo",
    "Goth Phulji",
    "Goth Radhan",
    "Gujar Khan",
    "Gujranwala",
    "Gujranwala Division",
    "Gujrat",
    "Gulishah Kach",
    "Gwadar",
    "Hadali",
    "Hafizabad",
    "Hala",
    "Hangu",
    "Haripur",
    "Harunabad",
    "Harnai",
    "Harnoli",
    "Hasan Abdal",
    "Hasilpur",
    "Hattian Bala",
    "Hattian Bala District",
    "Haveli Lakha",
    "Hazro",
    "Hingorja",
    "Hujra Shah Muqeem",
    "Hyderabad",
    "Islamabad",
    "Islamkot",
    "Jacobabad",
    "Jahanian Shah",
    "Jalalpur Jattan",
    "Jalalpur Pirwala",
    "Jamshoro",
    "Jampur",
    "Jam Sahib",
    "Jand",
    "Jandiala Sher Khan",
    "Jaranwala",
    "Jati",
    "Jauharabad",
    "Jawangarh",
    "Jawanwala",
    "Jhawarian",
    "Jhelum",
    "Jhol",
    "Jiwani",
    "Johi",
    "Kabirwala",
    "Kadhan",
    "Kahna Nau",
    "Kahuta",
    "Kalabagh",
    "Kalaswala",
    "Kaleke Mandi",
    "Kalat",
    "Kalāt District",
    "Kallar Kahar",
    "Kalur Kot",
    "Kamalia",
    "Kamar Mushani",
    "Kamoke",
    "Kamra",
    "Kandhkot",
    "Kandiari",
    "Kandiaro",
    "Kanganpur",
    "Karachi",
    "Karaundi",
    "Karor",
    "Kario Ghanwar",
    "Kasur",
    "Keshupur",
    "Keti Bandar",
    "Khadro",
    "Khairpur",
    "Khairpur Mir’s",
    "Khairpur Nathan Shah",
    "Khairpur Tamiwali",
    "Khalabat",
    "Khandowa",
    "Khangarh",
    "Khanga Dogran",
    "Khanewal",
    "Khanpur",
    "Khanpur Mahar",
    "Kharan",
    "Kharian",
    "Khewra",
    "Khushab",
    "Khuzdar",
    "Khuzdār District",
    "Kohat",
    "Kohlu",
    "Kohror Pakka",
    "Kot Addu Tehsil",
    "Kot Diji",
    "Kot Ghulam Muhammad",
    "Kotli",
    "Kotli District",
    "Kotli Loharan",
    "Kot Mumin",
    "Kot Radha Kishan",
    "Kot Rajkour",
    "Kot Samaba",
    "Kot Sultan",
    "Kudiani",
    "Kundian",
    "Kunri",
    "Kunjah",
    "Lachi",
    "Ladhewala Waraich",
    "Lahore",
    "Lala Musa",
    "Lalian",
    "Lakki",
    "Larkana",
    "Lasbela District",
    "Layyah",
    "Layyah District",
    "Liliani",
    "Lodhran",
    "Loralai",
    "Loralai District",
    "Mach",
    "Madeji",
    "Mailsi",
    "Malakwal",
    "Malakwal City",
    "Malir Cantonment",
    "Mamu Kanjan",
    "Mananwala",
    "Mansehra",
    "Mangla",
    "Mankera",
    "Mardan",
    "Mastung",
    "Mastung District",
    "Matli",
    "Mehar",
    "Mehrabpur",
    "Mehmand Chak",
    "Mian Channun",
    "Mianke Mor",
    "Mianwali",
    "Mingora",
    "Miran Shah",
    "Miro Khan",
    "Mirpur",
    "Mirpur Bhtoro",
    "Mirpur District",
    "Mirpur Khas",
    "Mirpur Mathelo",
    "Mirpur Sakro",
    "Mirwah Gorchani",
    "Mitha Tiwana",
    "Mithi",
    "Moza Shahwala",
    "Multan",
    "Multan District",
    "Muridke",
    "Murree",
    "Mustafabad",
    "Muzaffarābād",
    "Muzaffargarh",
    "Nabisar",
    "Nankana Sahib",
    "Narang Mandi",
    "Nasīrābād District",
    "Nasirabad",
    "Naudero",
    "Naukot",
    "Naushahro Firoz",
    "Naushahra Virkan",
    "Nawabshah",
    "Nazir Town",
    "New Bādāh",
    "New Mirpur",
    "Noorabad",
    "North Wazīristān Agency",
    "Nowshera",
    "Nowshera Cantonment",
    "Nushki",
    "Okara",
    "Ormara",
    "Pabbi",
    "Pad Idan",
    "Pakki Shagwanwali",
    "Pakpattan",
    "Pano Aqil",
    "Paharpur",
    "Pasni",
    "Pasrur",
    "Pattoki",
    "Peshawar",
    "Phalia",
    "Pind Dadan Khan",
    "Pindi Bhattian",
    "Pindi Gheb",
    "Pir Jo Goth",
    "Pir Mahal",
    "Pishin",
    "Qadirpur Ran",
    "Qila Didar Singh",
    "Quetta",
    "Quetta District",
    "Rabwah",
    "Rahim Yar Khan",
    "Rahimyar Khan District",
    "Raiwind",
    "Raja Jang",
    "Rajanpur",
    "Rajo Khanani",
    "Ranipur",
    "Rasulnagar",
    "Ratodero",
    "Rawala Kot",
    "Rawalpindi",
    "Rawalpindi District",
    "Renala Khurd",
    "Risalpur Cantonment",
    "Rohri",
    "Rojhan",
    "Rustam",
    "Sadiqabad",
    "Sahiwal",
    "Samaro",
    "Sambrial",
    "Sanghar",
    "Sangla Hill",
    "Sanjwal",
    "Sann",
    "Sarai Alamgir",
    "Sarai Naurang",
    "Sarai Sidhu",
    "Sargodha",
    "Shabqadar",
    "Shahdad Kot",
    "Shahdadpur",
    "Shahr Sultan",
    "Shahkot Tehsil",
    "Shahpur",
    "Shahpur Chakar",
    "Shakargarh",
    "Sharqpur",
    "Shikarpur",
    "Shingli Bala",
    "Shinpokh",
    "Shorkot",
    "Shujaabad",
    "Sialkot",
    "Sillanwali",
    "Sinjhoro",
    "Sita Road",
    "Sobhodero",
    "Sodhra",
    "Sohbatpur",
    "South Wazīristān Agency",
    "Sukheke Mandi",
    "Sukkur",
    "Surab",
    "Surkhpur",
    "Swabi",
    "Tando Adam",
    "Tando Allahyar",
    "Tando Bago",
    "Tando Jam",
    "Tando Mitha Khan",
    "Tando Muhammad Khan",
    "Tangwani",
    "Tangi",
    "Tank",
    "Talagang",
    "Talamba",
    "Talhar",
    "Taunsa",
    "Thal",
    "Tharu Shah",
    "Thatta",
    "Thul",
    "Toba Tek Singh",
    "Topi",
    "Turbat",
    "Ubauro",
    "Upper Dir",
    "Usta Muhammad",
    "Utmanzai",
    "Uthal",
    "Umarkot",
    "Umerkot",
    "Umerkot District",
    "Wah",
    "Warah",
    "Warburton",
    "Wana",
    "Wazirabad",
    "West Punjab",
    "Yazman",
    "Zafarwal",
    "Zahir Pir",
    "Zhob",
    "Zhob District",
    "Ziarat",
    "Ziārat District",
  ],
};

const selectablesSlice = createSlice({
  name: "Selectables",
  initialState,
  reducers: {
    fetchCities: (state, { payload }) => {
      state.cities = payload;
    },
    fetchStates: (state, { payload }) => {
      state.states = payload;
    },
  },
});

export const { fetchCities, fetchStates } = selectablesSlice.actions;
export default selectablesSlice.reducer;
