const services = [
    {
      title: "Air Conditioner Services",
      description: "Complete installation, service, and repair solutions for air conditioners.",
      subServices: [
        { title: "AC Dismounting / Removal" },
        { title: "AC General Service" },
        { title: "AC Installation" },
        { title: "AC Master Service" },
        { title: "AC Repair" },
      ],
    },
    {
      title: "Appliance Installation & Repair",
      description: "Installation and repair services for home appliances including kitchen and laundry units.",
      subServices: [
        { title: "Dishwasher Repair" },
        { title: "Fridge / Refrigerator / Freezer Repair" },
        { title: "Gas Heater Installation" },
        { title: "Kitchen Hood Repair" },
        { title: "Microwave / Cooking Range Repair" },
        { title: "Washing Machine Repair" },
        { title: "Water Dispenser Repair" },
      ],
    },
    {
      title: "Car General Services",
      description: "Interior and exterior detailing for all car types.",
      subServices: [
        { title: "Crossover General Service (Detailing)" },
        { title: "Hatchback General Service (Detailing)" },
        { title: "Sedan General Service (Detailing)" },
        { title: "SUV General Service (Detailing)" },
      ],
    },
    {
      title: "Carpentry & Woodwork",
      description: "Customized woodwork, installation, and repair solutions.",
      subServices: [
        { title: "Cabinet Installation / Repair" },
        { title: "Door Installation" },
        { title: "Furniture Repair / Renovation" },
        { title: "Kitchen Cabinet Installation / Repair" },
        { title: "Lock Installation / Repair" },
        { title: "Sofa Upholstery & Repair" },
        { title: "Wardrobe Installation / Repair" },
        { title: "Window Installation" },
        { title: "Wooden Flooring Installation / Repair" },
        { title: "General Woodwork Services" },
      ],
    },
    {
      title: "Electrician Services",
      description: "Electrical installations, repair and troubleshooting for home and office.",
      subServices: [
        { title: "Breaker Installation" },
        { title: "Distribution Box Installation / Repair" },
        { title: "Electric Heater Repair" },
        { title: "Electric Iron Repair" },
        { title: "Electrical Wiring Installation / Repair" },
        { title: "Fan Installation" },
        { title: "Fan Repair" },
        { title: "Fuse Box Installation / Repair" },
        { title: "Generator Installation / Repair" },
        { title: "Lights Installation" },
        { title: "Socket / Switchboard Installation / Repair" },
        { title: "UPS Installation (Without Wiring)" },
        { title: "UPS Repair" },
        { title: "Water Pump / Motor Repair" },
        { title: "Other Electrical Services" },
      ],
    },
    {
      title: "Geyser Installation, Service & Repair",
      description: "Complete installation and maintenance of gas and electric geysers.",
      subServices: [
        { title: "Electric Geyser Dismounting" },
        { title: "Electric Geyser Installation" },
        { title: "Electric Geyser Repair" },
        { title: "Electric Geyser Service" },
        { title: "Gas Geyser Installation" },
        { title: "Gas Geyser Repair" },
        { title: "Gas Geyser Service" },
        { title: "Instant Geyser Installation" },
        { title: "Instant Geyser Repair" },
        { title: "Instant Geyser Service" },
      ],
    },
    {
      title: "Grey Structure Services",
      description: "Construction of commercial and residential grey structures.",
      subServices: [
        { title: "Commercial Building Construction" },
        { title: "Residential Building Construction" },
      ],
    },
    {
      title: "Home Finishing Services",
      description: "End-to-end finishing including electrical, plumbing, flooring and painting.",
      subServices: [
        { title: "Electrical Services" },
        { title: "Painting Services" },
        { title: "Plumbing Services" },
        { title: "Flooring Services" },
      ],
    },
    {
      title: "Painting, Wallpaper & Furniture Polish",
      description: "Interior and exterior painting, polish, and wallpaper installation services.",
      subServices: [
        { title: "Deco Paint" },
        { title: "False Ceiling Installation / Repair" },
        { title: "Furniture / Wood Polish" },
        { title: "Wall Painting" },
        { title: "Wallpaper Installation" },
        { title: "Other Painting & Decoration Services" },
      ],
    },
    {
      title: "Home Repair & Maintenance",
      description: "General home maintenance, renovation, and repair solutions.",
      subServices: [
        { title: "Carpet Installation / Repair" },
        { title: "Curtain Installation / Repair" },
        { title: "Home Renovation" },
        { title: "House / Office Maintenance & Repair" },
        { title: "Office Renovation" },
        { title: "Other Handyman Services" },
      ],
    },
    {
      title: "Leakage, Seepage & Heat Proofing",
      description: "Protection against water leakage, seepage, and excessive heat.",
      subServices: [
        { title: "Bathroom Leakage / Seepage Repair" },
        { title: "Roof Heat Proofing" },
        { title: "Roof Leakage / Seepage Repair" },
        { title: "Roof Waterproofing" },
        { title: "Wall Dampness (Saim / Kular) Treatment" },
      ],
    },
    {
      title: "Pest Control",
      description: "Eradication and protection from pests like termites, insects, and rodents.",
      subServices: [
        { title: "Fumigation Services" },
        { title: "Household Insect Eradication" },
        { title: "Termite Control" },
      ],
    },
    {
      title: "Plumbing Services",
      description: "Installation and repair of all plumbing fixtures and piping systems.",
      subServices: [
        { title: "Automatic Washing Machine Installation" },
        { title: "Bathroom Accessories Installation / Repair" },
        { title: "Commode Installation" },
        { title: "Cooking Range Installation" },
        { title: "Dishwasher Installation" },
        { title: "Gas Pipe Installation / Repair" },
        { title: "Kitchen Accessories Installation" },
        { title: "Kitchen Sink Installation / Repair" },
        { title: "Shower Installation / Replacement" },
        { title: "Tap Installation / Replacement" },
        { title: "Water Motor / Pump Installation" },
        { title: "Water Pipe Installation / Repair" },
        { title: "Water Tank Installation" },
        { title: "Other Plumbing Services" },
      ],
    },
    {
      title: "Professional Cleaning",
      description: "Specialized cleaning services for home, carpets, sofas, and water tanks.",
      subServices: [
        { title: "Deep Cleaning Services" },
        { title: "Professional Carpet Cleaning" },
        { title: "Curtain Cleaning" },
        { title: "Home Cleaning Service" },
        { title: "Mattress Dry & Cleaning Service" },
        { title: "Water Tank Cleaning (300 Gallons)" },
        { title: "Water Tank Cleaning (500 Gallons)" },
        { title: "Sofa Cleaning & Drying" },
      ],
    },
    {
      title: "Solar Panel Installation & Maintenance",
      description: "Solar energy system installation, repair, and regular maintenance services.",
      subServices: [
        { title: "Complete Solar System Installation" },
        { title: "Solar Inverter Installation" },
        { title: "Battery Installation / Replacement" },
        { title: "Solar Panel Cleaning & Maintenance" },
        { title: "Net Metering Setup Assistance" },
        { title: "Solar System Troubleshooting & Repair" },
      ],
    },
    {
      title: "Welding, Glass, Aluminium & Metal Work",
      description: "Customized work related to welding, glass fitting, aluminum, and metal structures.",
      subServices: [
        { title: "Aluminum / Glass Work" },
        { title: "Glass Door Installation / Repair" },
        { title: "Glass Wall Installation / Repair" },
        { title: "Iron Gate Installation / Repair" },
        { title: "Iron Grill Installation / Repair" },
        { title: "Metal Fabrication Work" },
        { title: "General Welding Services" },
      ],
    },
  ];
  